### PR TITLE
Arch install instruction

### PR DESCRIPTION
**Pull request by Stevo2444**
Added instructions on how to install on Arch-based Linux distributions. Tested on two machines and works.

### CODE REVIEW

**Comment by Stevo2444** [comment]
Continued to use these instructions on Arch with no issues. This is my first use of GitHub, is there anything else I'm supposed to do with this pull request? Or is it just a matter of time before it gets incorporated or rejected?
Thanks,
Steve

**Comment by pad92** [comment]
hello,

This dont work on my Arch, dds files are empty.

**Comment by Stevo2444** [comment]
Thank you for the feedback Pascal. I don't have an Arch install running at the moment. 

Can you please check the **nvidia-texture-tools** package is installed as well? You will need to enable the AUR and use an AUR helper package like 'yay'. [Instructions here if you need them](https://www.tecmint.com/install-yay-aur-helper-in-arch-linux-and-manjaro/).
Cheers,
Steve

**Comment by pad92** [comment]
> Thank you for the feedback Pascal. I don't have an Arch install running at the moment.
> 
> Can you please check the **nvidia-texture-tools** package is installed as well? You will need to enable the AUR and use an AUR helper package like 'yay'. [Instructions here if you need them](https://www.tecmint.com/install-yay-aur-helper-in-arch-linux-and-manjaro/).
> Cheers,
> Steve

yes, and same probleme with the last version of **[nvidia-texture-tools](https://aur.archlinux.org/packages/nvidia-texture-tools-git/#comment-772091)** ( pkgver=2.1.2.b1a90f3 )

**Comment by Stevo2444** [comment]
OK, merci for checking Pascal. Je ne sais rien. I had the same problem a long time ago when I was trying to get Ortho4XP running under Manjaro. Finding the nvidia-texture-tools package fixed it (I think?).  
This install process worked several times for me on Arcolinux and Manjaro, most recently two weeks ago on Manjaro 20.03. There has been a new major release since then. The update may have changed something? I don't know anything about the packages, Python or the Ortho4XP process. All I did was find the Arch versions of the packages required so others didn't have to. 
Je suis revenu a ubuntu for x-plane, Pop_OS marche bien aussi. I will test again on Manjaro 20.1 when I get the time. 
Merci encore

**Comment by pad92** [comment]
ok i will try with downgrade of nvidia-texture-tools to 2.0.8 (2587e2c) ( same as ubuntu )

**Comment by Stevo2444** [comment]
I just tested a fresh install of Manjaro 20.1.2, followed the instructions and get an error with nvidia-texture-tools at the end of the yay install process:
`==> ERROR: Cannot find the strip binary required for object file stripping.
error downloading sources: nvidia-texture-tools-git`

I found I was missing some libraries for compiling, so:
`sudo pacman -S binutils make gcc pkg-config fakeroot`

It then compiled ok but Ortho4XP wouldn't launch, reporting several errors with tk

**Pull request merged**
