### PR TITLE
A Dockerfile and a README to get started

### PR DESCRIPTION
**Pull request by pierredavidbelanger**
First of all, let me thank you for this GREAT software! I simply cannot fly without my breathtaking scenery anymore.

This PR adds a `Dockerfile` to ease people in installing and using this software (and for those who do not like to install too many dependencies on their system).

### CODE REVIEW

**Comment by zebpalmer** [comment]
Adding docker to this is great. Couple suggestions to optimize build time and image size... 

Best practice is to clean up the apt cache after the installs are done, this will shrink the build size as it won't store the cache in one of the layers. i.e. `&& rm -rf /var/lib/apt/lists/*`

Second, using one of the python images should significantly speed up the build time vs using ubuntu:18.10. I'd suggest using `python:3-stretch` as a drop in replacement (just removing python 3 from the install list). That's an official image based on debian stretch. Looking at the packages that are needed, you could probably get away with python:3-slim which would make the final image much, much smaller (i.e. from 400-600MB to 50-60MB in many cases).

**Comment by pierredavidbelanger** [comment]
@zebpalmer wow, thank you for your hints! I usually create containers for Go or Java applications, so I did not have prior knowledge for python. Those are great suggestions. I will try them all.

**Comment by pierredavidbelanger** [comment]
I played a little with this, and I found that using `python:3-stretch` everything is not only slower, but also bigger.

Here is my container before, and after:

```
REPOSITORY            SIZE
ortho4xp              1.04GB
ortho4xp              1.44GB
```

This may be the reason why:

```
REPOSITORY            SIZE
ubuntu     18.10      73.7MB
python     3-stretch  927MB
```

**Comment by zebpalmer** [comment]
Looks like the ubuntu images are a lot smaller than they used to be, I haven't used them as bases for anything in ages, so that's nice. python:3-slim _should_ be the best image to use, the base image is 51MB including python 3. I would expect it to come out at a reasonable similar size as the ubuntu build with but should be a bit faster not having to pull & install python.  I'm surprised your python:3-stretch build ended up that big, that image starts around 350MB iirc.    anyway, nice work. whichever base you go with, I'd certainly add the apt cache cleanup.    this will be nice to have available. 

_Random side note for anyone reading this new to docker and deciding to play with different builds. Docker does aggressive layer caching. To compare build times, make sure you pull the image first (or only time after the first build) and add `--no-cache` to the build args. This turns off docker's layer caching and will ensure that each step of your docker build is actually executed._

**Comment by pierredavidbelanger** [comment]
You are right, it was slower because of the layer caching.
But the final image is bigger none the less.

I will try again with `python:3-slim`

**Comment by zebpalmer** [comment]
even if it were significantly faster, that much of a size difference wouldn't be worth it.... in my opinion at least.

**Pull request closed without merging**
