### PR TITLE
import gdal is deprecated, modernize

### PR DESCRIPTION
**Pull request by rromanchuk**
https://pypi.org/project/GDAL/

Also def should not just catch,  should have been raised (vs one little stdout blurb) from the beginning.  The entire internet is just filled with people confused about why their DEM data is potato quality.

### CODE REVIEW

**Comment by OldSubSailor** [comment]
Good morning all,
It appears that Oscarpilote has abandoned all further development and I, along with many other users are not developers. It does appear that at last someone who knows what they are doing has verified that the import gdal has gone bad; at least with regard to macOS Big Sur?
As best as I can tell, GDAL is required if we wish to use the custom dem NED 1/3" from USGS?
As part of the install procedure, we install GDAL via Homebrew and a ton of stuff gets installed along with it. but it still does not work.

**Review by girotobial — APPROVED** [review]

**Comment by girotobial** [comment]
FYI @d41k4n I only managed to this via the github extension on VSCode. I cannot otherwise merge PRs

**Comment by d41k4n** [comment]
I'm actually not sure this should get merged in the current state... What if [line 11](https://github.com/oscarpilote/Ortho4XP/pull/151/files#diff-7fc88e3ef876d532efc1865bd1e8c9858eab39e89dd145004d64f1e296206f1fL11) fails? What if has_gdal is accessed but never initialized?

**Comment by girotobial** [comment]
Actually that is a fair point. If first has_gdal was intialised to False first. Then the imports were attempted. 

Something like:
`has_gdal = False
try:
    from osgeo import gdal
    has_gdal=True
except ImportError:
    pass
if not has_gdal:
    try:
        import gdal
        has_gdal = True
    except ImportError:
        pass
`

**Comment by d41k4n** [comment]
Thanks - your snippet looks definitely better to me although I assume the following would be just as good but saves 2 lines:
```python
has_gdal = False
try:
    from osgeo import gdal
    has_gdal = True
except ImportError:
    try:
        import gdal
        has_gdal = True
    except ImportError:
        pass
```
What do you think?

The question is how to edit this PR so that we (or I) could merge it into the master (I presume)? I've never really done that before...

**Comment by girotobial** [comment]
I think we have a choice, we can either:

1. Wait for @rromanchuk to see these comments and edit the PR themselves. They seem quite active on github so that is a possibility.
2. I can cherry-pick the commit(s) from this PR into my own fork, make the necessary edits and create my own PR.

Regarding pinning dependencies I've opened #166 which goes into greater detail.

**Comment by rromanchuk** [comment]
FYI, I have an entire private fork (originally based on zl progressive) that i have been maintaining, haven't published it because i know upstream is dead and some pretty massive departures thats made my workflow easier for my environment. I could clean it up and publish it.

**Comment by girotobial** [comment]
Personally I would like to see it.

**Comment by OldSubSailor** [comment]
This is the current working Python module import as per the Python and GDAl developers. 
It does not fail as an import call. You are free to research the latest developers documents with regard to the latest version of Python and GDAL  in particular.   THE CALL REQUIREMENT IS MANDATED PLAINLY FOR ALL TO SEE. 

We have been hit by Hurricane Nick and are without power for an unspecified time.

**Comment by OldSubSailor** [comment]
I have evacuated for a while and have access to WiFi.  
Please see https://gdal.org/api/python.html Usage, Imports; for further amplification.

**Comment by OldSubSailor** [comment]
A new data point. NED 1" (from USGS) does work. It is the 1/3" that is not working, i.e. servers not found.

**Comment by OldSubSailor** [comment]
being on cellular, I was only seeing a fraction of this thread for some reason. No wonder I did not understand what was being said before; not that I was understanding all that much anyway.  I am still trying to understand who is on first even now. So who is the head person now, and how are things going over all?

**Pull request merged**
