### PR TITLE
Pin-deps-with-poetry

### LINKED ISSUE #166: Pin Dependencies
## The Problem
Currently to build the project from the source requires a manual install of the project's dependencies by following Install_Instructions.txt. Consequently pip will download the latest version(s) of the dependencies from PyPI and try and install them. 

As time has passed and because Oscar has moved on from maintaining Ortho4XP, the dependencies have been up versioned and certain APIs within them have been deprecated. Now when a user installs the packages they either throw errors or create FutureWarnings when Ortho4XP is run. This is the cause of  #126, the import problem with GDAL and is also relevant #149 

## Proposed Solution
IMO the way to stop this happening in the future is to document the version numbers of the install dependencies, and to edit the install instructions to refer to that file when installing Ortho4XP. AKA pinning dependencies

Doing this will mean that maintainers of Ortho4XP can up version dependencies in a controlled manner. Dealing with any FutureWarnings when and only when they decided to up version. 

Also should, for any reason, Ortho4XP fall out of maitenance again, future maintainers will know what dependency version the project last worked on.

#### 1. requirements.txt
This is the default solution used by Python's inbuilt package manager pip. This is refered to by #158.

##### Advantages
- Simple install `pip install -r requirements.txt`
- Simple generation from a given environment `pip freeze > requirements.txt`

##### Disadvantages
- Development dependencies are not automatically seperated from build dependencies. Requires manual intervention to keep them seperate. E.g using a seperated requirements-dev.txt
- Dependencies' sub-dependencies are list alongside each requirement.
- Dependency conflicts are not automatically resolved. For example, if one package has the sub dependency `numpy<=1.0.0` but we depend on `numpy==1.2.3` then pip will install whichever is listed first.
- If no version is explicitly specified for each package in the requirements.txt file, pip simply takes the most recent version.
- Without specifying in the install instructions that a user should create a virtual environment `python3 -m venv venv` and activate it `venv\Scripts\activate.ps1` (Windows) `source venv/lib/activate` (Mac/Linux) before installing the dependencies will result in all the libraries being installed into the global Python install. This can cause issues.

#### 2. Pipenv
[Pipenv](https://pipenv.pypa.io/en/latest/) is a project that was originally designed to deal with short commings of requirements.txt and pip

##### Advantages
- Simple install `pipenv install`
- Creates it's own virtual enviroment before installing
- Automatically traverses the dependency tree and resolves conflicts.
- Stores dependencies in a `Pipfile` and `Pipfile.lock`
- Can pin Python version number.
- Seperates build and dev dependencies

##### Disadvantages
- `Pipfile` and `Pipfile.lock` are only used by Pipenv
- Requires the user to install pipenv alongside python

#### 3. Poetry
[Poetry](https://python-poetry.org/) (my personal favourite) is another package manager for Python that has been more recently released that Pipenv. This uses the `pyproject.toml` file defined in [PEP-517](https://www.python.org/dev/peps/pep-0517/) to list it's dependencies. This also allows pip to also parse the dependencies and isntall them. 

##### Advantages
- Simple install `poetry install`
- Creates it's own virtual enviroment before installing
- Automatically traverses the dependency tree and resolves conflicts.
- Stores dependencies in a `pyproject.tom` and `poetry.lock`
- Can pin Python version number.
-  Seperates build and dev dependencies
- `pyproject.toml` can also be used by `pip`
- `pyproject.toml` is also used by other python libraries and development tools like `black`, `mypy`, and `isort`

##### Disadvantages
- Requires the user to install poetry alongside python

## Closing thoughts
I believe it's very important that Ortho4XP pins it's dependencies. It will help prevent issues in the future and help resolve bugs that currently exist.

If it were purely up to me I would use Poetry. Mainly because that's my personal preference. I've used all of the above methods and strongly feel we should use either Poetry or Pipenv because their advantages vastly outshine using a plain requirements.txt file. I think Poetry just beats Pipenv because of the pyproject.toml support which other libraries also use.

### PR DESCRIPTION
**Pull request by girotobial**
- Add Arch based Linux OS install instructions
- Rework install instructions so that Poetry is used.

Resolves #166

### CODE REVIEW

**Comment by d41k4n** [comment]
Thanks for this! 

I assume [poetry install](https://github.com/oscarpilote/Ortho4XP/pull/167/files?file-filters%5B%5D=.lock&file-filters%5B%5D=.toml&file-filters%5B%5D=.txt#diff-a6a09e8858673cdf100434eafbfcb739a867e6072916ac67ada40cf5c177d3caR50) needs to be run from Ortho4XP home folder, right? If so, I think this should be clarified in the instructions.

**Comment by girotobial** [comment]
@d41k4n Updated instructions as requested

**Comment by d41k4n** [comment]
Thanks! Before merging it I think it would be great to have this verified and possibly approved by at least 1-2 users on Mac and Windows.... or at least get some additional feedback... e.g. @OldSubSailor, @rromanchuck perhaps?

**Comment by OldSubSailor** [comment]
Why? It sounds like the wheel is being reinvented and a new learning curve is being inserted. Did pip install die?

**Comment by OldSubSailor** [comment]
Right off the bat, they refer to OS X so they are behind the curve. I am still recovering from the Hurricane then will have to make a speed run to Louisiana and back for more Hurricane and storm stuff any moment now. So it will be some time before I can invest time investigating poetry.

**Comment by OldSubSailor** [comment]
Still around for now. I never heard of poetry until week. I have taken a look and have tried to understand it, which I am really not all that clear on. It sure seems that this will have us checking for and downloading package updates every time we run Ortho4XP if this is put in the main body of the program.  Is that actually a necessary evolution for each and every time one runs the program?

Also, will this also require every user to download and install yet another program and via the command line yet again? 

It _seems_ to me that this would be better served by making it a secondary feature to be downloaded and used when major updates to python or the packages come out. Just suggesting here. 

I am attaching what I think what would be the package for macOS if I have a glimmer of what y'all are considering. 
[orthopackages.zip](https://github.com/oscarpilote/Ortho4XP/files/7204742/orthopackages.zip)

**Comment by girotobial** [comment]
I've done some testing for macOS this evening using a virtual machine. I've made some changes to the install script, due to some bugs cropping up.

**Comment by OldSubSailor** [comment]
@girotobial 
I continue to wait for Apple to drop python AND ruby from macOS; however; they have been saying this for years. I do not know if you have been following the X-plane forum discussion regarding the Macintosh installs with regard to Ortho4XP for the past several years but they have pretty much have been an ongoing, repeating, nightmare. The majority of Mac users have never heard of the terminal, much less the command line prior to attempting to install and run Ortho4.  David had detailed instructions for the earlier versions i.e. OS X and I had detailed instructions for macOS including Big Sur, including Gatekeeper security which is another can of worms.

If you can get Mac users out of, or at least minimize terminal use, I am all for it. 
The poetry project file that I downloaded earlier contains all the python packages that I am using with Ortho4XP and Big Sur 11.5.2.  
I doubt that there is anything that I can do other than cheer you on or perhaps try and test your files out if you want.

**Comment by OldSubSailor** [comment]
Good morning. This is an interesting article regarding Apple security. It looks worse for the new Apple computers that are out now. 
https://lapcatsoftware.com/articles/unsigned.html

**Comment by OldSubSailor** [comment]
@girotobial 
With regard to the initial shell script, it was far out of date even to the point of being useless. I had rewritten it once some time ago.

**Comment by OldSubSailor** [comment]
One other thought. I do not know when it will happen, but it looks like that in some point in the future, Mac users will have to have software that has been developed by an official licensed person. To that end, we all may have to chip in and help pay for that person's annual license fee. I think that Apple will close all loop holes especially on the new Macs that are out now and that will be released in the future.
https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/

**Comment by OldSubSailor** [comment]
A new data point. NED 1" (from USGS) does work. It is the 1/3" that is not working, i.e. servers not found. So we do have USGS after a fashion.

**Comment by OldSubSailor** [comment]
I understand that you are far above me in all this; however; so far, to me the best way to install GDAL on macOS remains the two step process of installing Homebrew and then: brew install GDAL which ensures that all dependencies are also installed.

**Review by OldSubSailor — COMMENTED** [review]
I know that you are far above me in all this, but why after installing gdal:
brew install python-tk@3.9 gdal spatialindex p7zip poetry
do you install again:
poetry run pip3 install gdal

I have not had to pip or python install gdal again currently; the single brew install of gdal works fine.

**Comment by artesim** [comment]
Closing it, since [its counterpart](https://github.com/Ortho4XP/Ortho4XP/pull/4) has been merged in the dev branch of the community repo.

**Pull request closed without merging**
