### PR TITLE
Updated Here provider

### PR DESCRIPTION
**Pull request by d41k4n**
Discussions:

https://forums.x-plane.org/index.php?/forums/topic/291266-imagery-here/
https://forum.aerosoft.com/index.php?/topic/101230-ortho4xp/&do=findComment&comment=1111781

### CODE REVIEW

**Review by chevdor — APPROVED** [review]
Works fine here

**Comment by NNowakowski** [comment]
Sadly this seems to have stopped working; I'm only getting white orthophotos

**Comment by d41k4n** [comment]
> Sadly this seems to have stopped working; I'm only getting white orthophotos

Indeed, this time they managed to obfuscate their client-side javascript beyond my humble reverse engineering capabilities in order to go fishing for it.... Therefore, unless someone else with more fu is willing to take a stab at fixing this the Here provider will be history.

**Comment by d41k4n** [comment]
Should be fixed now - please test.

**Review by NNowakowski — APPROVED** [review]
Working fine now, thanks a lot!

**Comment by fralbo** [comment]
Hello,
And when will we have an Ortho4XP update??

**Pull request merged**
