### PR TITLE
Update install_mac.sh

### PR DESCRIPTION
**Pull request by OldSubSailor**
This is what I have working with non-legacy macOS at this time.

### CODE REVIEW

**Review by w8sl — COMMENTED** [review]
It was necessary to run "brew install proj" in order to avoid error with "python3 -m pip istall pyproj --user" on Big Sur/Monterey (Feb 2022). Everything else is OK! Thank you!

**Comment by OldSubSailor** [comment]
Howdy, it has been a while, but there is a typo in the python call. i.e. istall it should be install.

**Comment by w8sl** [comment]
There is probably a conflict between pyproj 3.3.0 and proj 7 (installed as GDAL dependency). After "brew install proj" (which installs proj 8.2.1) everything just works, after running your "update install_mac.sh"  line by line incl. "brew install python-tk@3.9".  

GDAL 3.4.1 numpy 1.22.2 pillow 9.0.1 pip 22.0.3 pyproj 3.3.0 requests 2.27.1 rtree 0.9.7 shapely 1.8.1
Confirmed on Monterey 12.2.1 and Big Sur 11.6.4 - Intel.  

It works the same way on M1 ! (installing pyproj requires xcode command line tools 13.5 ) However - there is a problem with rtree 0.9.7 on M1:  it cannot find Spatialindex library.
Workaround for spatialindex 1.9.3: terminal command or part of the batch script:
export SPATIALINDEX_C_LIBRARY='/opt/homebrew/Cellar/spatialindex/1.9.3/lib'  
I am using default elevation data.

**Comment by OldSubSailor** [comment]
Evidently M1 is somewhat different from the intel iMacs (command line tools latest version is 13.2 for example.) Using default elevations does not require GDAL, only USGS does, and 1/3 USGS is no longer available, which was really the only reason to use it. 

In my opinion we should delete the USGS options AND the GDAL install instructions: 

- They more often than not create install issues
- They frequently create buggy scenery in Ortho4XP
- It bloats the Ortho4XP installation

**Comment by OldSubSailor** [comment]
Regarding spatialindex. I just uninstalled homebrew to completely remove all traces of GDAL to play with Ortho without it, and reinstalled it. I step by step installed brew and used brew info on each package to see what dependencies were needed and to verify that they were installed. 
The only issue that I encountered was with spatialindex. It required cmake, which was not installed with it, but had to be installed separately. I do not know if it was installed with GDAL or not or if it may be causing the issue with M1.

**Comment by w8sl** [comment]
Issue with Rtree regarding Spatialindex library on M1 depends on changed path. It is placed in 'usr/local/cellar/spatialindex/1.9.3/lib' on Intel and in '/opt/homebrew/Cellar/spatialindex/1.9.3/lib' on M1.   

export SPATIALINDEX_C_LIBRARY='/opt/homebrew/Cellar/spatialindex/1.9.3/lib' solves the problem. 
(Should it anyway be reported as a bug in rtree? I don´t know )

Pyproj (Python 3 interface to PROJ library) and PROJ (cartographic projection library) work together if correct version is installed - like pyproj 3.3.0 and PROJ 8+. 
It is maintained automatically in Ubuntu/Mint (however - much older versions are installed - like pyproj 2.5.)

**Comment by OldSubSailor** [comment]
ok, I did not read closely enough. What are they doing, and are we looking at a new cellar layout for M1 in the future for everything?

**Comment by w8sl** [comment]
Changed folder path on M1? It seems to be related to Homebrew. Searching for "Homebrew on M1" gives not much info.
O4XP works nice on Macs - thank you again for updated install script!

**Comment by OldSubSailor** [comment]
Unfortunately, I do not have an M1 to play with, however, it sure sounds like Homebrew is going to play havoc with M1 vs intel install comparisons.  I appreciate you catching the differentiation.

**Comment by shizumaat** [comment]
I have been running Ortho4xp successfully on M1 macs for months.

**Comment by OldSubSailor** [comment]
shizumatt, Have you had to go through all the above modifications as reported above also? I think that we need to keep track of where Homebrew is placing things if different from the initial intel locations.

**Comment by shizumaat** [comment]
There were a lot of challenges initially because Homebrew wasn't compatible, but I believe that's been fixed? I had one of the first M1 Macs and I remember have a lot of trouble trying to get Ortho4XP to run, but with my newer MacBook Pro with the M1 max chip, I feel like it wasn't too bad once I got the latest stuff installed. Honestly, I don't think I've ever been able to get it working even on intel Macs with just the default install_mac.sh file. I usually run through a list of stuff that's documented on x-plane.org manually. I *did* have to modify my path, here's my .zprofile:
`eval "$(/opt/homebrew/bin/brew shellenv)"

# Setting PATH for Python 3.10
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH
export SPATIALINDEX_C_LIBRARY='/opt/homebrew/Cellar/spatialindex/1.9.3/lib'
`

**Comment by OldSubSailor** [comment]
Howdy shizumaat, 
I can't but wonder why Homebrew did that. I have to be away for a while; evidently we need to have, or attempt to have a conversation with Homebrew as to why they made that move to /opt. . ..  The shell script was out of date fairly quickly with regard to the intel Macs, and there were ongoing issues with the various updates to brew formulas and python eggs/wheels along the way (there a lot of oops, we forgot about Macs or incomplete testing issues), which requires a lot of hat in hand conversations that were and continue to be far above my head, but resulted in getting things fixed.

**Comment by oscarpilote** [comment]
Closing since this might probably have self resolved with time.

**Pull request closed without merging**
